language: python
python:
  - "3.5"
  - "3.6"
env:
  - TRAVIS=yes
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda install --yes -c r rpy2 r-randomforest
  - conda install --yes python=$TRAVIS_PYTHON_VERSION --file requirements.txt
  - pip install pytest pytest-cov
  - pip install coveralls
install:
  - travis_retry python setup.py dev
script: travis_wait py.test --runslow
after_success:
  - coveralls
cache: apt


